### PR TITLE
Moe Sync

### PR DESCRIPTION
**Pull request by ronshapiro**
This code has been reviewed and submitted internally. Feel free to discuss on the PR and we can submit follow-up changes as necessary.

Commits:
=====
<p> Enable GoodTime API checker for Flogger

RELNOTES=suppress goodtime-api violations

9a681df3408464ebd003c9a0c7126042dc80648e

-------

<p> Make gen_platform_provider deterministic

because this uses the default jar tool, it encodes timestamps in the jar files

The easiest thing is just to have the tool directly produce the jar file instead of trying to use a jar tool

4080f60bd2573eac8f4c5282f3ac4d4dce2d6245

### CODE REVIEW

**Comment by jbduncan** [comment]
In commit https://github.com/google/flogger/commit/9a681df3408464ebd003c9a0c7126042dc80648e, am I right to assume that "GoodTime" is an internal Google tool?

If so, I wonder if it would be possible and desirable to remove the `@SuppressWarning("GoodTime")` annotations in the public version of Flogger, so as to reduce potential confusion in the future? :thinking:

**Comment by jbduncan** [comment]
Oh - I see that Guava has a forthcoming commit [here](https://github.com/google/guava/pull/3298) to introduce lots of `@SuppressWarning("GoodTime")`s as well, so I'd understand if removing them weren't desirable after all.

**Comment by ronshapiro** [comment]
@jbduncan GoodTime is a suite of ErrorProne checks we're developing. They're not ready for primetime, but we do expect them to get there, at which point these suppressions will be helpful :)

**Comment by jbduncan** [comment]
That sounds both very reasonable and rather exciting! So thanks for clarifying things for me @ronshapiro. Looking forward to GoodTime's public release. :)

**Comment by jbduncan** [comment]
(...Am I right to infer that GoodTime will see a public release?) 😃❓

**Pull request merged**
